name: Build

on:
  push:
  pull_request:
    branches: master      
  workflow_dispatch:
    inputs:
      
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        channel:
          - nightly
          # - stable
        target-triple:
          - x86_64-unknown-linux-gnu
        include:
          - target-triple: x86_64-unknown-linux-gnu
            host-triple: x86_64-unknown-linux-gnu
            features: "sqlite"
            channel: nightly
            os: ubuntu-20.04

    name: Building ${{ matrix.channel }}-${{ matrix.target-triple }}
    runs-on: ${{ matrix.os }}
    steps:

      - name: Set Environment Variables
        uses: deep-mm/set-variables@v1.0

      - name: Create /etc/resolv.conf 
        run: |
          RESOLVCONF="/etc/resolv.conf"
      
          sudo cat $RESOLVCONF
          sudo rm -f $RESOLVCONF
          sudo touch $RESOLVCONF
          sudo echo "nameserver 8.8.8.8" >> $RESOLVCONF
          sudo echo "nameserver 8.8.4.4" >> $RESOLVCONF
          
      #- name: Update system packages
      #  run: sudo apt update -y 
      #  
      #- name: Install resolveconf
      #  run: sudo apt install resolvconf -y 
      #  
      #- name: Get resolveconf.service status
      #  run: sudo systemctl status resolvconf.service
      #       
      #- name: Print /run/resolvconf/resolv.conf
      #  run: cat /run/resolvconf/resolv.conf
      #  
      #- name: Print /etc/resolve.conf (Pre symbolic link) 
      #  run: sudo cat /etc/resolve.conf
      #  continue-on-error: true
      #   
      #- name: Create resolve.conf symbolic link
      #  run: sudo ln -sf /run/resolvconf/resolv.conf /etc/resolv.conf
      #  
      #- name: Print /etc/resolve.conf (Post symbolic link) 
      #  run: sudo cat /etc/resolve.conf

      - name: Environment 
        run: printenv | sort

      - name: Download latest artifact from a github workflow
        uses: benday-inc/download-latest-artifact@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: dani-garcia 
          repository_name: bitwarden_rs
          workflow_name: Build
          branch_name: master
          download_path: /home/runner/dist
          download_filename: bitwarden.zip
          
      - name: Extract bw-data directory
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: /home/runner/dist/bitwarden.zip
          pathTarget: ${{ secrets.DATA_FOLDER }}


      - name: One Click Docker
        uses: pangzineng/Github-Action-One-Click-Docker@v1.1.1
        with:
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Login to Docker
      #  uses: docker/login-action@latest
      #  with:
      #    #registry: ${{ secrets.DOCKER_REGISTRY }}
      #    registry: reg.dockerize.io
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    logout: true
          
      #- name: Build and push Docker images
      #  uses: docker/build-push-action@v2.4.0
      #  env:
      #    SMB_USERNAME: ${{ secrets.SMB_USERNAME }}
      #    SMB_PASSWORD: ${{ secrets.SMB_PASSWORD }}
      #    DATA_FOLDER: ${{ secrets.DATA_FOLDER }}
      #  with:          
      #    tags: ${{ secrets.repo }}/${{ secrets.username }}/bitwardenrs
          
