name: Build

on:
  push:
  pull_request:
    branches: master      
  workflow_dispatch:
    inputs:
      
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        channel:
          - nightly
          # - stable
        target-triple:
          - x86_64-unknown-linux-gnu
        include:
          - target-triple: x86_64-unknown-linux-gnu
            host-triple: x86_64-unknown-linux-gnu
            features: "sqlite"
            channel: nightly
            os: ubuntu-20.04

    name: Building ${{ matrix.channel }}-${{ matrix.target-triple }}
    runs-on: ${{ matrix.os }}
    steps:

      - name: Set Environment Variables
        uses: deep-mm/set-variables@v1.0
        with:
          variableFileName: global

      - name: View Environment Vartiables
        run: printenv | sort

      - name: Create /etc/resolv.conf 
        run: |
          RESOLVCONF="/etc/resolv.conf"
      
          sudo cat $RESOLVCONF
          sudo rm -f $RESOLVCONF
          sudo touch $RESOLVCONF
          sudo echo "nameserver 8.8.8.8" >> $RESOLVCONF
          sudo echo "nameserver 8.8.4.4" >> $RESOLVCONF

      - name: Docker Extract
        # You may pin to the exact commit or the version.
        # uses: shrink/actions-docker-extract@7d86f1b9adc7afe4a64e13fb425872a547d6afa3
        uses: shrink/actions-docker-extract@v1
        with:
          # Docker Image to extract files from
            image: ${{ env.BITWARDEN_IMAGE }}
          # Path (from root) to a file or directory within Image
          path: 

      - name: Download latest artifact from a github workflow
        uses: benday-inc/download-latest-artifact@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository_owner: dani-garcia 
          repository_name: bitwarden_rs
          workflow_name: Build
          branch_name: master
          download_path: ${{ env.DIST_ROOT}}
          download_filename: ${{ env.DIST_FILENAME }}
          
      - name: Extract bw-data directory
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{ env.DIST_ROOT }}${{}}
          pathTarget: ${{ env.DATA_FOLDER }}


      - name: One Click Docker
        uses: pangzineng/Github-Action-One-Click-Docker@v1.1.1
        with:
          DOCKER_REGISTRY_URL: ${{ env.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Login to Docker
      #  uses: docker/login-action@latest
      #  with:
      #    #registry: ${{ secrets.DOCKER_REGISTRY }}
      #    registry: reg.dockerize.io
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    logout: true
          
      #- name: Build and push Docker images
      #  uses: docker/build-push-action@v2.4.0
      #  env:
      #    SMB_USERNAME: ${{ secrets.SMB_USERNAME }}
      #    SMB_PASSWORD: ${{ secrets.SMB_PASSWORD }}
      #    DATA_FOLDER: ${{ secrets.DATA_FOLDER }}
      #  with:          
      #    tags: ${{ secrets.repo }}/${{ secrets.username }}/bitwardenrs
          
